### ISSUE TITLE
[BUG] Metrics UX Tracking List

### ISSUE THREAD

**Issue by pjfitzgibbons** [opensearch-project/dashboards-observability#1053]
**What is the bug?**
The following items are found during UX review of Metrics Inline Edit (#940)

- [ ] * Make removing the selected metric more intuitive
  - [ ]     * Add “Remove from List” to context menu
- [ ] * Investigate taking away [x] from Atributes multi-select
- [ ] * Edit view / remove button - bug - not working
- [ ] * User Intuition of workflow is not acceptable?    
  - [ ]     * Figure out a plan to avoid saving to legacy dashboard (broken) - must be new dashboard only
  - [ ]     * Can’t create new dashboard from Save box (type in new name)
    - [ ]         * Docs team can write up workflow
- [ ] * Seach-box tooltip change size to match save-box tooltips
- [ ] * Ensure multiple vis can be added to a dashboard multiple ways
  - [ ]     * From dashboard - add
  - [ ]     * From metrics - save to blank dashboard
  - [ ]     * From metrics - save to populated dashboard
