### ISSUE TITLE
[FEATURE][Metrics] 2.12 Integration Tracking List

### ISSUE THREAD

**Issue by pjfitzgibbons** [opensearch-project/dashboards-observability#1084]
## What is the feature?
This is a tracking list of integrations from [metrics demo branch](https://github.com/opensearch-project/dashboards-observability/tree/feature/metrics-editor-and-promql-demo-nov6-141300), to be piece-wise merged to `main` by individual PRs

Included is a list of anomolies or inconsistencies in functionality or UX/CSS on 2.11 release branch.

Demo of updated functionality and workflows :
https://github.com/opensearch-project/dashboards-observability/assets/11318/6a0ec086-8b6e-4f6b-904a-c377b58a1f7e

###  UX-discovered bugs 
- [X] Log Explorer / Visualization workflow is broken - can't load PromQL Visualization/Metric
- [ ] Log Explorer List initial load shows zero-items splash page, then renders list.
- [X] Metrics / Metric Export Panel
  - [X] Don't display "legacy" dashboards to save.  Legacy dashboards don't work for metric save.

### Commits to integrate

- [ ] 4a42a682 Metrics Export display links to saved dashboards on toast success
- [ ] bbf06103 Metrics save to OSD Dashboards from Metrics Export Panel
- [ ] 874bc172 Save PPLVis "AsMetric" to OSD SavedObjects.  Display PPL-Metrics on Metric Explorer list and OSD Dashboards Visualizations List
- [ ] 12bf95d2 URL-selected metric loads only itself on Metrics Explorer
- [ ] 8b835ed6 OSD Dashboard embedded Metric "Edit" navigates to Metrics module
- [ ] 7ef5252f SizeMe debugging
- [ ] 03ba7c7e Correct Display of PPL Visualization / Metrics on OSD Dashboard
- [ ] 00524abf MetricGrid Visualizations reload on Span/Resolution Change
- [ ] 3bfba88a Convert MetricsGrid redux usage to redux.connect
- [ ] 39b7e2fc Display Metric in OSD Dashboards
- [ ] e3a9147c Log Explorer table links Metric type to Metric Explorer
- [ ] 1b6485db MetricSlice mapped list
- [ ] 8a89f4e2 MetricInlineEdit move to slot on VisualizationContainer
- [ ] 24ab187e Metric Visualization by meta-data, savedVisualization, both MetricGrid and Dashboard
- [ ] 23744e84 Display PromQl saved obejct in Log Explorer / Visualization (graph WIP)
- [ ] d34f9fb6 Metric Inline Edit reload query when attributes change
- [ ] 9a35ffc8 Metrics Inline Editor and PromQL Parsing

**Comment by YANG-DB** [comment]
attempting to get Prometheus metrix:`aws_prometheus6.prometheus_http_requests_total`

Got this error
<img width="1764" alt="Screenshot 2023-10-05 at 12 32 00 PM" src="https://github.com/opensearch-project/dashboards-observability/assets/48943349/16d11714-9f83-4555-a09d-da6540a4db07">

```
Failed to parse query due to offending symbol [2023] at: 'source = aws_prometheus6.query_range('avg | where @timestamp >= '2023' <--- HERE... More details: Expecting tokens in {'SEARCH', 'DESCRIBE', 'SHOW', 'FROM', 'WHERE', 'FIELDS', 'RENAME', 'STATS', 'DEDUP', 'SORT', 'EVAL', 'HEAD', 'TOP', 'RARE', 'PARSE', 'METHOD', 'REGEX', 'PUNCT', 'GROK', 'PATTERN', 'PATTERNS', 'NEW_FIELD', 'KMEANS', 'AD', 'ML', 'SOURCE', 'INDEX', 'D', 'DESC', 'DATASOURCES', 'SORTBY', 'STR', 'IP', 'NUM', 'KEEPEMPTY', 'CONSECUTIVE', 'DEDUP_SPLITVALUES', 'PARTITIONS', 'ALLNUM', 'DELIM', 'CENTROIDS', 'ITERATIONS', 'DISTANCE_TYPE', 'NUMBER_OF_TREES', 'SHINGLE_SIZE', 'SAMPLE_SIZE', 'OUTPUT_AFTER', 'TIME_DECAY', 'ANOMALY_RATE', 'CATEGORY_FIELD', 'TIME_FIELD', 'TIME_ZONE', 'TRAINING_DATA_SIZE', 'ANOMALY_SCORE_THRESHOLD', 'NOT', 'TRUE', 'FALSE', 'CONVERT_TZ', 'DATETIME', 'DAY', 'DAY_HOUR', 'DAY_MICROSECOND', 'DAY_MINUTE', 'DAY_OF_YEAR', 'DAY_SECOND', 'HOUR', 'HOUR_MICROSECOND', 'HOUR_MINUTE', 'HOUR_OF_DAY', 'HOUR_SECOND', 'INTERVAL', 'MICROSECOND', 'MILLISECOND', 'MINUTE', 'MINUTE_MICROSECOND', 'MINUTE_OF_DAY', 'MINUTE_OF_HOUR', 'MINUTE_SECOND', 'MONTH', 'MONTH_OF_YEAR', 'QUARTER', 'SECOND', 'SECOND_MICROSECOND', 'SECOND_OF_MINUTE', 'WEEK', 'WEEK_OF_YEAR', 'YEAR', 'YEAR_MONTH', '.', '+', '-', '(', '`', 'AVG', 'COUNT', 'DISTINCT_COUNT', 'ESTDC', 'ESTDC_ERROR', 'MAX', 'MEAN', 'MEDIAN', 'MIN', 'MODE', 'RANGE', 'STDEV', 'STDEVP', 'SUM', 'SUMSQ', 'VAR_SAMP', 'VAR_POP', 'STDDEV_SAMP', 'STDDEV_POP', 'PERCENTILE', 'TAKE', 'FIRST', 'LAST', 'LIST', 'VALUES', 'EARLIEST', 'EARLIEST_TIME', 'LATEST', 'LATEST_TIME', 'PER_DAY', 'PER_HOUR', 'PER_MINUTE', 'PER_SECOND', 'RATE', 'SPARKLINE', 'C', 'DC', 'ABS', 'CBRT', 'CEIL', 'CEILING', 'CONV', 'CRC32', 'E', 'EXP', 'FLOOR', 'LN', 'LOG', 'LOG10', 'LOG2', 'MOD', 'PI', 'POSITION', 'POW', 'POWER', 'RAND', 'ROUND', 'SIGN', 'SQRT', 'TRUNCATE', 'ACOS', 'ASIN', 'ATAN', 'ATAN2', 'COS', 'COT', 'DEGREES', 'RADIANS', 'SIN', 'TAN', 'ADDDATE', 'ADDTIME', 'CURDATE', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURTIME', 'DATE', 'DATEDIFF', 'DATE_ADD', 'DATE_FORMAT', 'DATE_SUB', 'DAYNAME', 'DAYOFMONTH', 'DAYOFWEEK', 'DAYOFYEAR', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'EXTRACT', 'FROM_DAYS', 'FROM_UNIXTIME', 'GET_FORMAT', 'LAST_DAY', 'LOCALTIME', 'LOCALTIMESTAMP', 'MAKEDATE', 'MAKETIME', 'MONTHNAME', 'NOW', 'PERIOD_ADD', 'PERIOD_DIFF', 'SEC_TO_TIME', 'STR_TO_DATE', 'SUBDATE', 'SUBTIME', 'SYSDATE', 'TIME', 'TIMEDIFF', 'TIMESTAMP', 'TIMESTAMPADD', 'TIMESTAMPDIFF', 'TIME_FORMAT', 'TIME_TO_SEC', 'TO_DAYS', 'TO_SECONDS', 'UNIX_TIMESTAMP', 'UTC_DATE', 'UTC_TIME', 'UTC_TIMESTAMP', 'WEEKDAY', 'YEARWEEK', 'SUBSTR', 'SUBSTRING', 'LTRIM', 'RTRIM', 'TRIM', 'LOWER', 'UPPER', 'CONCAT', 'CONCAT_WS', 'LENGTH', 'STRCMP', 'RIGHT', 'LEFT', 'ASCII', 'LOCATE', 'REPLACE', 'REVERSE', 'CAST', 'LIKE', 'ISNULL', 'ISNOTNULL', 'IFNULL', 'NULLIF', 'IF', 'TYPEOF', 'MATCH', 'MATCH_PHRASE', 'MATCH_PHRASE_PREFIX', 'MATCH_BOOL_PREFIX', 'SIMPLE_QUERY_STRING', 'MULTI_MATCH', 'QUERY_STRING', 'ALLOW_LEADING_WILDCARD', 'ANALYZE_WILDCARD', 'ANALYZER', 'AUTO_GENERATE_SYNONYMS_PHRASE_QUERY', 'BOOST', 'CUTOFF_FREQUENCY', 'DEFAULT_FIELD', 'DEFAULT_OPERATOR', 'ENABLE_POSITION_INCREMENTS', 'ESCAPE', 'FLAGS', 'FUZZY_MAX_EXPANSIONS', 'FUZZY_PREFIX_LENGTH', 'FUZZY_TRANSPOSITIONS', 'FUZZY_REWRITE', 'FUZZINESS', 'LENIENT', 'LOW_FREQ_OPERATOR', 'MAX_DETERMINIZED_STATES', 'MAX_EXPANSIONS', 'MINIMUM_SHOULD_MATCH', 'OPERATOR', 'PHRASE_SLOP', 'PREFIX_LENGTH', 'QUOTE_ANALYZER', 'QUOTE_FIELD_SUFFIX', 'REWRITE', 'SLOP', 'TIE_BREAKER', 'TYPE', 'ZERO_TERMS_QUERY', 'SPAN', 'MS', 'S', 'M', 'H', 'W', 'Q', 'Y', ID, INTEGER_LITERAL, DECIMAL_LITERAL, DQUOTA_STRING, SQUOTA_STRING, BQUOTA_STRING}
```

**Comment by anirudha** [comment]
https://github.com/opensearch-project/dashboards-observability/assets/19362/f854d47b-de92-4585-b58f-d3bb4c212650

**Comment by Swiddis** [comment]
Closing as stale since 2.12 was a while ago
